Add parquet2sql
src-d/parquetry pull request #1
Opened 2019-10-24 14:27 UTC by Guillemdb

Signed-off-by: Guillem Duran <guillem@sourced.tech>

2019-10-25 14:02 UTC, vmarkovtsev requested changes

2019-10-25 14:02 UTC, vmarkovtsev commented on README.md
> -# parquetry
Hehe, we should have a title in the README

2019-10-25 14:02 UTC, vmarkovtsev commented on parquet2sql/__main__.py
> +    parser = get_parser()
Can you please move these to `def main()` - that way we can link it as an entry point in `setup.py`

2019-10-25 14:02 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
> +    return 0
This is looking weird, we'd rather convert from None to 0 in `def main()`

2019-10-25 17:13 UTC, Guillemdb commented on parquet2sql/parquet2sql.py
> +    return 0
Sure. I just copy pasted Konst's code. I will update it.

2019-10-28 15:03 UTC, Guillemdb commented on parquet2sql/__main__.py
> +    parser = get_parser()
Done

2019-10-28 15:15 UTC, vmarkovtsev requested changes

2019-10-28 15:15 UTC, vmarkovtsev commented on README.md
> -# parquetry
Not really resolved, still removed :D

2019-10-28 15:15 UTC, vmarkovtsev commented on setup.py
> +    license="Proprietary",
Apache 2.0

2019-10-28 15:15 UTC, vmarkovtsev commented on setup.py
> +        "License :: Propietary license",
```suggestion
        "License :: OSI Approved :: Apache Software License",
```

2019-10-28 15:15 UTC, vmarkovtsev commented on setup.py
> +        "Programming Language :: Python :: 3.7",
```suggestion
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
```

2019-10-28 15:22 UTC, Guillemdb commented
What should I do with the README? Doesn't already look like it should? https://github.com/Guillemdb/parquetry?organization=Guillemdb&organization=Guillemdb

2019-10-28 15:36 UTC, vmarkovtsev approved these changes

2019-10-28 15:36 UTC, merged