Add incremental update
src-d/parquetry pull request #3
Opened 2019-10-29 10:15 UTC by Guillemdb

Signed-off-by: src-d <src-d@sourced.tech>

2019-10-29 10:15 UTC, Guillemdb commented
Closes https://github.com/src-d/parquetry/issues/2

2019-10-29 10:16 UTC, Guillemdb commented
If you like the structure I will add type hinting, comments and tests, but I wanted to be sure the code make sense first.

2019-10-29 15:09 UTC, vmarkovtsev requested changes

2019-10-29 15:09 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
>  from sqlalchemy import create_engine
```suggestion
```
Let's kill this import then

2019-10-29 15:09 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
> +        self.log.info("File %s saved to table %s at %s", parquet, table, self.db)
```suggestion
        self.log.info("File %s was saved to table %s at %s", parquet, table, self.db)
```

2019-10-29 15:09 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
> +            raise KeyError("`op` not in dataframe columns.")
```suggestion
            raise KeyError("There must be an `op` column in the Parquet table.")
```

2019-10-29 15:09 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
> +            raise KeyError("`op` not in dataframe columns.")
```suggestion
            raise KeyError("There must be an `op` column in the Parquet table.")
```

2019-10-29 15:09 UTC, vmarkovtsev commented on parquet2sql/parquet2sql.py
> +        add_data.to_sql(table, self.engine, if_exists='append', index=False)
```suggestion
        add_data.to_sql(table, self.engine, if_exists="append", index=False)
```

2019-10-30 11:24 UTC, vmarkovtsev approved these changes

2019-10-30 11:24 UTC, merged

2019-10-30 11:24 UTC, vmarkovtsev commented
@Guillemdb Please bump the version and I will push the new tag.